### ISSUE TITLE
How to make data persistent

### ISSUE THREAD

**Issue by kopax** [Zimbra-Community/zimbra-docker#5] opened 2015-10-08 15:16 UTC
Hi Jorge, do you have any recommendation for backuping and resotoring the container as it was ?

**Comment by barrydegraaff** [comment] 2016-02-26 13:47
Closing this as it is a duplicate of https://github.com/Zimbra-Community/zimbra-docker/issues/6

**Closed by barrydegraaff** 2016-02-26 13:47 UTC
